# Generated by Django 5.0.6 on 2024-07-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('companyid', models.AutoField(db_column='companyID', primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, null=True)),
                ('company_size', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'companies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('expertiseid', models.AutoField(db_column='expertiseID', primary_key=True, serialize=False)),
                ('expertise', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'expertise',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hirers',
            fields=[
                ('hirerid', models.AutoField(db_column='hirerID', primary_key=True, serialize=False)),
                ('hiring_team_name', models.CharField(blank=True, null=True)),
                ('hirer_job_title', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hirers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobConditions',
            fields=[
                ('conditionid', models.AutoField(db_column='conditionID', primary_key=True, serialize=False)),
                ('promoted_status', models.CharField(blank=True, null=True)),
                ('easy_apply_status', models.CharField(blank=True, null=True)),
                ('is_reposted', models.BooleanField(blank=True, null=True)),
                ('time_posted', models.CharField(blank=True, null=True)),
                ('scrapping_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'job_conditions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobDescriptions',
            fields=[
                ('descriptionid', models.AutoField(db_column='descriptionID', primary_key=True, serialize=False)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('list_of_skills', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'job_descriptions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobListings',
            fields=[
                ('jobid', models.BigAutoField(db_column='JobID', primary_key=True, serialize=False)),
                ('jobidlinkedin', models.BigIntegerField(blank=True, db_column='jobIDLinkedin', null=True)),
                ('applicants', models.IntegerField(blank=True, null=True)),
                ('years_experience', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'job_listings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobTypes',
            fields=[
                ('jobtypeid', models.AutoField(db_column='jobTypeID', primary_key=True, serialize=False)),
                ('job_type', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'job_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('locationid', models.AutoField(db_column='locationID', primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, null=True)),
                ('remote_status', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'locations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sectors',
            fields=[
                ('sectorid', models.AutoField(db_column='sectorID', primary_key=True, serialize=False)),
                ('sector', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sectors',
                'managed': False,
            },
        ),
    ]
